#!/bin/sh

export VISUAL=mtt-editor.sh
export EDITOR="$VISUAL"
alias edit="$VISUAL"

# $PATH update
case ":${PATH}:" in
    *:"$HOME/.local/bin":*)
        ;;
    *)
        export PATH="$PATH:$HOME/.local/bin"
        ;;
esac

# refresh profile
if [ -f $HOME/.bash_profile ]; then
    alias refresh-profile='source $HOME/.bash_profile'
else
    alias refresh-profile='source $HOME/.profile'
fi

# setup env flags
for c in emacs eza fastfetch git ruby rustc ; do
    U=SG_IS_${c^^}
    command -v $c 2>&1 >/dev/null
    declare $U=$?
done
unset c

# ####
if [ 0 == $SG_IS_EZA ]; then
    alias le='eza -l'
    alias lg='eza --long --grid'
    alias lt='eza --long --tree'
fi
# RUBY
if [ 0 == $SG_IS_RUBY ]; then
    alias rhttp='echo "http://localhost:8008" && ruby -run -e httpd -- -p 8008'
fi
# RUST
if [ 0 == $SG_IS_RUSTC ]; then
    RUSTC_LIBRARY_PATH=$(rustc --print=target-libdir)
    if ! [[ "$LD_LIBRARY_PATH" =~ "$RUSTC_LIBRARY_PATH" ]]
    then
        if [ -z "${LD_LIBRARY_PATH}" ]
        then
            LD_LIBRARY_PATH="$RUSTC_LIBRARY_PATH"
        else
            LD_LIBRARY_PATH="$RUSTC_LIBRARY_PATH:$LD_LIBRARY_PATH"
        fi
    fi
    export LD_LIBRARY_PATH
    export CROSS_ROOTLESS_CONTAINER_ENGINE=1 # use podman for cross build
fi
# MISC
if command -v static-web-server 2>&1 >/dev/null ; then
    alias shttp='env SERVER_ROOT=./ static-web-server -p 8008 -z "$@"'
fi
if command -v mise 2>&1 >/dev/null ; then
    eval "$(mise activate bash)"
fi
if command -v exiv2 2>&1 >/dev/null; then
    alias exiv='exiv2'
fi
if command -v zeditor 2>&1 >/dev/null ; then
    alias code='zeditor'
fi
if command -v zed 2>&1 >/dev/null ; then
    alias code='zed'
fi
